
OPENAI_API_KEY = sk-proj-"MsTyslVWyxgCwCUEIcqvWKp_pPnCTR8sxhuBETybvzCSlaLyerRVS7oBPsFPQg2AiddvUHYNNbT3BlbkFJ6Tr5VnG0yvpZu8W2OtvqkkOx6wR6SJs_xsB5n4vLo6SvMc82yEzjsWzW9PRJQNujXn8uvfmksA"
APP_PASSWORD = "らいが"